version: '3.7'

services:
  web:
    container_name: nginxtestovoe
    build:
      context: app/dockerFiles/nginx
    platform: linux/amd64
    ports:
      - "80:80"
    volumes:
      - ./:/projectX
    depends_on:
      - php
      - redis

  php:
    build: ./app/DockerFiles/php
    container_name: php_testovoe
    volumes:
      - ./:/projectX
    expose:
      - 9000

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./app/storage/redis:/data:delegated
